import { environment } from "src/environments/environment";

export const APIEndpoints = {
    menu: `${environment.apiHost}/api/menucontrols`,
    dailytip: `${environment.apiHost}/api/daily-peace-tips`,
    homebanner: `${environment.apiHost}/api/home-banners`,
    healthtips: `${environment.apiHost}/api/healthtips`,
    expertadvice: `${environment.apiHost}/api/expert-advices`,
    contactus: `${environment.apiHost}/api/contacts`,
    relations: `${environment.apiHost}/api/relationals`,
    peaceathome: `${environment.apiHost}/api/peaceathome`,
    nopeacepartnerviolence: `${environment.apiHost}/api/no-peace-home-contents`,
    servicefilteroptions: `${environment.apiHost}/api/service-filteroptions`,
    supportServiceDistances: `${environment.apiHost}/api/support-service-distances`,
    sliderapi: `${environment.apiHost}/api/home-sliders`,
    healthyrelationslider: `${environment.apiHost}/api/healthy-relationship-sliders`,
    healtyrelationTitleContent: `${environment.apiHost}/api/healthy-relationship`,
    healthyrelationcontentwithoutbutton: `${environment.apiHost}/api/healthyrelationshipcontents`,
    healthyrelationcontentwithbutton: `${environment.apiHost}/api/unhealthurelationshipcontents`,
    nopeaceathomeslider: `${environment.apiHost}/api/no-peaceat-home-sliders`,
    nopeaceathometitlecontent: `${environment.apiHost}/api/no-peaceat-home`,
    nopeacepartnerviolencecontent: `${environment.apiHost}/api/no-peace-home-contents`,
    nopeacehouseholdconflicts: `${environment.apiHost}/api/no-peace-home-house-conflicts`,
    nopeacetoxicrelationship: `${environment.apiHost}/api/no-peaceat-home-toxic-relationships`,
    peaceathomeslider: `${environment.apiHost}/api/peace-at-home-sliders`, 
    supportService: `${environment.apiHost}/api/support-services`, 
    unhealthyrelationshipbanner: `${environment.apiHost}/api/unhealthy-relationship`, 
    unhealthyrelationshipslider: `${environment.apiHost}/api/unhealthyrelationsliders`, 
    unhealthyrelationcontentone: `${environment.apiHost}/api/unhealthyrelationfirstcontents`, 
    unhealthyrelationcontenttwo: `${environment.apiHost}/api/unhealthyrelationsecondcontents`, 
    unhealthyrelationcontentthree: `${environment.apiHost}/api/unhealthyrelationthirdcontents`, 
    federallawbannercontent: `${environment.apiHost}/api/federal-level-law`, 
    legalrightsbannercontent: `${environment.apiHost}/api/legal-right`,
    uvisa: `${environment.apiHost}/api/u-visas`, 
    tvisa: `${environment.apiHost}/api/t-visas`, 
    childwaiver: `${environment.apiHost}/api/child-waivers`, 
    immigrationbenfit: `${environment.apiHost}/api/immigration-benefits`, 
    usstatelaws: `${environment.apiHost}/api/us-state-laws`,
    partnervioencehome: `${environment.apiHost}/api/partner-violence-title`,
    ipvpartnervioence: `${environment.apiHost}/api/partnerviolencecontents`,
    typesOfAbuse: `${environment.apiHost}/api/types-of-abuse`,
    typesofabusesTitle :`${environment.apiHost}/api/typesof-abuse-title`,
    ipvtypesofabuses :`${environment.apiHost}/api/ipvtypesofabuses`,
    physicalabuse :`${environment.apiHost}/api/physical-abuses`,
    sexualabuse :`${environment.apiHost}/api/sexual-abuses`,
    emotionalabuse :`${environment.apiHost}/api/emotional-abuses`,
    verbalabuse :`${environment.apiHost}/api/verbal-abuses`,
    financialabuse :`${environment.apiHost}/api/financial-abuses`,
    technologicalabuse :`${environment.apiHost}/api/technological-abuses`,
    immigrantabuse :`${environment.apiHost}/api/immigrant-abuses`,
    systemabuse :`${environment.apiHost}/api/system-abuses`,
    unhealthyrelationexamples :`${environment.apiHost}/api/unhealthyrelationexamples`,
    criminalizationOfSurvivors :`${environment.apiHost}/api/criminizalationof-survivors`,
    quiz :`${environment.apiHost}/api/quizzes`,
    sripa :`${environment.apiHost}/api/sripaas`,
    ssripaQuestions :`${environment.apiHost}/api/ssripa-questions`,
    ssripGuidUrl :`${environment.apiHost}/api/generate-ssripa-guid`,
    
    
    //Risk assessment modules
    userLogins :`${environment.apiHost}/api/user-logins`,
    loginbyemail :`${environment.apiHost}/api/user-logins/login`,
    changePassword :`${environment.apiHost}/api/user-logins/change-password`,
    forgetPw :`${environment.apiHost}/api/auth/forgot-password`,
    hitsAssessmentQuestions :`${environment.apiHost}/api/hits-assessment-questions`,
    scaleOptions :`${environment.apiHost}/api/multiple-answer-options`,
    hitsresultcalculation :`${environment.apiHost}/api/hit-results`,
    saveHitsAssessment :`${environment.apiHost}/api/hits-assessment-responses`,
    hitsGuidUrl :`${environment.apiHost}/api/generate-hits-guid`,
    
    // WEB assessment
    ratsAssessmentQuestions :`${environment.apiHost}/api/rat-assessment-questions`,
    ratScaleOptions :`${environment.apiHost}/api/multiple-options-for-rats`,
    ratResultCalculation :`${environment.apiHost}/api/rat-results`,
    saveRatAssessment: `${environment.apiHost}/api/rat-assessment-response-summaries`,
    ratResult :`${environment.apiHost}/api/rat-assessment-response-summaries/by-assessment-number?AssessmentGuid=`,
    webGuidUrl :`${environment.apiHost}/api/generate-web-guid`,
    
    DAAssesmentQuestions :`${environment.apiHost}/api/da-assessment-questions`,
    daAssessmentQuestions :`${environment.apiHost}/api/da-assessment-questions`,
    daAssessmentResult :`${environment.apiHost}/api/da-score-levels`,
    daAssessmentResponse :`${environment.apiHost}/api/da-assessment-responses`,
    daGuidUrl :`${environment.apiHost}/api/generate-da-guid`,

    //Get by Guid url
    getDaAssessmentByGuid :`${environment.apiHost}/api/da-assessment-responses/by-guid?AssessmentGuid=`,
    getHitsAssessmentByGuid :`${environment.apiHost}/api/hits-assessment-responses/by-guid?AssessmentGuid=`,
    getSSripaAssessmentByGuid :`${environment.apiHost}/api/ssripa-assessment-responses/by-guid?AssessmentGuid=`,

    getConfig :`${environment.apiHost}/api/configs`,
    errorLogger: `${environment.apiHost}/api/error-logger`,
    saveSSripaAssessment: `${environment.apiHost}/api/ssripa-assessment-responses`
  }
