import { environment } from "src/environments/environment";

export const APIEndpoints = {
    menu: `${environment.apiHost}/api/menucontrols`,
    dailytip: `${environment.apiHost}/api/daily-peace-tips`,
    homebanner: `${environment.apiHost}/api/home-banners`,
    healthtips: `${environment.apiHost}/api/healthtips`,
    expertadvice: `${environment.apiHost}/api/expert-advices`,
    contactus: `${environment.apiHost}/api/contacts`,
    relations: `${environment.apiHost}/api/relationals`,
    peaceathome: `${environment.apiHost}/api/peaceathome`,
    nopeacepartnerviolence: `${environment.apiHost}/api/no-peace-home-contents`,
    servicefilteroptions: `${environment.apiHost}/api/service-filteroptions`,
    sliderapi: `${environment.apiHost}/api/home-sliders`,
    healthyrelationslider: `${environment.apiHost}/api/healthy-relationship-sliders`,
    healtyrelationTitleContent: `${environment.apiHost}/api/healthy-relationship`,
    healthyrelationcontentwithoutbutton: `${environment.apiHost}/api/healthyrelationshipcontents`,
    healthyrelationcontentwithbutton: `${environment.apiHost}/api/unhealthurelationshipcontents`,
    nopeaceathomeslider: `${environment.apiHost}/api/no-peaceat-home-sliders`,
    nopeaceathometitlecontent: `${environment.apiHost}/api/no-peaceat-home`,
    nopeacepartnerviolencecontent: `${environment.apiHost}/api/no-peace-home-contents`,
    nopeacehouseholdconflicts: `${environment.apiHost}/api/no-peace-home-house-conflicts`,
    nopeacetoxicrelationship: `${environment.apiHost}/api/no-peaceat-home-toxic-relationships`,
    peaceathomeslider: `${environment.apiHost}/api/peace-at-home-sliders`, 
    supportService: `${environment.apiHost}/api/support-services`, 
    unhealthyrelationshipbanner: `${environment.apiHost}/api/unhealthy-relationship`, 
    unhealthyrelationshipslider: `${environment.apiHost}/api/unhealthyrelationsliders`, 
    unhealthyrelationcontentone: `${environment.apiHost}/api/unhealthyrelationfirstcontents`, 
    unhealthyrelationcontenttwo: `${environment.apiHost}/api/unhealthyrelationsecondcontents`, 
    unhealthyrelationcontentthree: `${environment.apiHost}/api/unhealthyrelationthirdcontents`, 
    federallawbannercontent: `${environment.apiHost}/api/federal-level-law`, 
    uvisa: `${environment.apiHost}/api/u-visas`, 
    tvisa: `${environment.apiHost}/api/t-visas`, 
    childwaiver: `${environment.apiHost}/api/child-waivers`, 
    immigrationbenfit: `${environment.apiHost}/api/immigration-benefits`, 
    usstatelaws: `${environment.apiHost}/api/us-state-laws`,
    partnervioencehome: `${environment.apiHost}/api/partner-violence-title`,
    ipvpartnervioence: `${environment.apiHost}/api/partnerviolencecontents`,
    typesOfAbuse: `${environment.apiHost}/api/types-of-abuse`,
    typesofabusesTitle :`${environment.apiHost}/api/typesof-abuse-title`,
    ipvtypesofabuses :`${environment.apiHost}/api/ipvtypesofabuses`
  }